import Head from "next/head";
export default function Home() {
  return (
    <div>
      <Head>
        <title>보일러 플레이트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>보일러 플레이트</h1>
        <p>nextjs, react query, emotion, typescript, zustand</p>
        <p>theme, type alias,</p>
      </main>
    </div>
  );
}
