import landingImage from "@assets/images/landing_image.png";
import { Button } from "@components/common";
import { Thumbnail } from "@components/icons";
import styled from "@emotion/styled";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>보일러 플레이트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <LogoWrapper>
          <Thumbnail width={20} height={20} />
          <LogoName>타임투밋</LogoName>
        </LogoWrapper>
        <Header>
          <p>매번 날짜 투표 만들지 말고</p>
          카톡으로 하는 <br /> 모임시간 자동 매칭
        </Header>
        <LogoBiggerWrapper>
          <Thumbnail />
          <p>타임투밋</p>
        </LogoBiggerWrapper>
        <Button width={"20rem"} onClick={() => router.push("/new")}>
          새로운 모임 만들기
        </Button>
        <Image src={landingImage} width={294} height={515} alt={"모임"} />
      </Layout>
    </div>
  );
}

const Layout = styled.div`
  width: 100%;
  max-width: 42.8rem;
  display: flex;
  align-items: center;
  flex-direction: column;
  margin: 0 auto;
  padding: 1.5rem 2rem;
`;

const Header = styled.header`
  font-size: 2.6rem;
  color: ${(props) => props.theme.colors.primary};
  line-height: 1.2;
  text-align: center;
  margin: 3rem 0rem;
  font-weight: 700;

  & > p {
    font-weight: 400;
    font-size: 2rem;
    margin-bottom: 0.5rem;
  }
`;

const LogoWrapper = styled.div`
  display: flex;
  justify-content: flex-start;
  width: 100%;
  align-items: center;
  margin-bottom: 9rem;
`;

const LogoBiggerWrapper = styled(LogoWrapper)`
  justify-content: center;
  font-size: 2.6rem;
  align-items: center;
  & > p {
    text-align: center;
    margin: 3rem 0rem;
    font-weight: 700;
    margin-left: 1rem;
  }
  margin-bottom: 0rem;
`;

const LogoName = styled.div`
  color: ${(props) => props.theme.colors.primary};
  font-size: 2rem;
  margin-left: 0.8rem;
  font-weight: 700;
`;
